enabled_layouts fat:bias=70;full_size=1;mirrored=false

map cmd+up resize_window taller
map cmd+down resize_window shorter
map cmd+shift+enter close_window
map cmd+1 next_window

## font_family 72Mono-Regular

modify_font cell_height 2px
font_size 13.0

shell_integration disabled

macos_titlebar_color dark

window_logo_path background.png
window_logo_position bottom-right
window_logo_alpha 1
window_logo_scale 100

# Nightfox colors for Kitty
## name: ui5conlightfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/ui5conlightfox/kitty.conf

background #FFF8F0
foreground #000000
selection_background #ffba60
selection_foreground #000000
cursor_text_color #FFF8F0
url_color #719f41

# Cursor
# uncomment for reverse background
# cursor none
cursor #000000

# Border
active_border_color #e45314
inactive_border_color #646363
bell_border_color #0090da

# Tabs
active_tab_background #e45314
active_tab_foreground #ffffff
inactive_tab_background #ffba60
inactive_tab_foreground #646363

# normal
color0 #223548
color1 #ba066c
color2 #719f41
color3 #df8f25
color4 #e45314
color5 #8838ec
color6 #3b4673
color7 #ffffff

# bright
color8 #435363
color9 #c42b82
color10 #86ad5e
color11 #e4a046
color12 #e86d37
color13 #9a56ef
color14 #586288
color15 #ffffff

# extended colors
color16 #0090da
color17 #ba066c
