set -g mouse on

# set -g window-active-style bg=#242424

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind-key v split-window -h
bind-key Enter split-window -v

bind-key x kill-pane

bind-key k kill-session
